### ISSUE TITLE
Apply generator level filter for ttbar sample

### ISSUE THREAD

**Issue by jhgoh** [nurion4hep/KSC-RnD-2024-Transformer4MET#10]
ttbar sample이 inclusive인 경우 fully hadronic이 섞여 있어서 MET regression에 좋지 않음.

- 현재 사용중인 샘플에서는 다른 채널이 섞였는지 확인해야 함
- 다른 채널이 섞여 있다면 generator level filter 개발해 넣어야 함.

**Comment by jhgoh** [comment]
#9

**Comment by slowmoyang** [comment]
I generated dileptonic samples
