### ISSUE TITLE
fix the workflow config yaml file for mattermost notification

### ISSUE THREAD

**Issue by slowmoyang** [nurion4hep/KSC-RnD-2024-Transformer4MET#18]
I updated the config file through #16 because `PAYLOAD_FILE` input is deprecated.
However, when #17 was created, the action failed to find the `MATTERMOST_WEBHOOK_URL` secret.
I tried updating the secret and rerunning the action but the notification failed.

**Comment by slowmoyang** [comment]
When `issues`, `issue_comment` and writing comments on PR, the action is working...

**Comment by jhgoh** [comment]
Solved, #23 #24
