### ISSUE TITLE
First Cross checks on the environments

### ISSUE THREAD

**Issue by jhgoh** [nurion4hep/KSC-RnD-2024-Transformer4MET#3]
Perform the first cross checks to run the training scripts with the given samples, by students

- [x] Cross check by @JunwonTomOh 
- [x] Cross check by @sourcemaru
- [x] Cross check by @xoqhdgh1002

**Comment by JunwonTomOh** [comment]
Works well on my side.

**Comment by xoqhdgh1002** [comment]
Works well on my side.
Thanks.
________________________________
보낸 사람: JunwonTomOh ***@***.***>
보낸 날짜: 2024년 3월 26일 화요일 오전 2:53
받는 사람: nurion4hep/KRE-RnD-Transformer4MET ***@***.***>
참조: Bongho Tae ***@***.***>; Mention ***@***.***>
제목: Re: [nurion4hep/KRE-RnD-Transformer4MET] First Cross checks on the environments (Issue #3)


Works well on my side.

**Comment by slowmoyang** [comment]
@jhgoh can u add @sourcemaru and @xoqhdgh1002 to nurion4hep? they are not in the organisation.

**Comment by jhgoh** [comment]
> @jhgoh can u add @sourcemaru and @xoqhdgh1002 to nurion4hep? they are not in the organisation.

Done!
