### ISSUE TITLE
notify github issue

### ISSUE THREAD

**Issue by slowmoyang** [nurion4hep/KSC-RnD-2024-Transformer4MET#4]
update https://github.com/nurion4hep/KRE-RnD-Transformer4MET/blob/main/.github/scripts/notify.py to notify github issue

**Comment by jhgoh** [comment]
Should I change something in the settings? I guess everything is already set up

**Comment by slowmoyang** [comment]
I'm happy with the current settings. I just need to implement a function creating a note when an issue is created.

**Comment by slowmoyang** [comment]
check https://github.com/cpnr/computing/blob/main/.github/workflows/mattermost.yml

**Comment by slowmoyang** [comment]
implemented through #16
