### ISSUE TITLE
Copy the file from Neuron to External

### ISSUE THREAD

**Issue by JunwonTomOh** [nurion4hep/KSC-RnD-2024-Transformer4MET#5]
Cannot copy the file from neuron to external server
Both scp & rsync didn't work

**Comment by jhgoh** [comment]
실행 명령어와 에러 메시지를 여기에 붙여주세요.

**Comment by JunwonTomOh** [comment]
This command was run on Neuron.
`rsync -avzr --progress -e 'ssh -p 2222' ./logs junwonoh@hep.khu.ac.kr:/users/junwonoh/KRE/. `

Errors:
```
ssh: connect to host hep.khu.ac.kr port 2222: Connection timed out
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.2]
```

**Comment by jhgoh** [comment]
ssh로 외부로 접속이 잘 안되네요.. neuron -> lxplus 접속도 멈춰 있음.
```
[x2719a01@glogin03 ~]$ ssh lxplus.cern.ch -l jhgoh -vvv
OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017
debug1: Reading configuration data /home01/x2719a01/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 59: Applying options for *
debug2: resolving "lxplus.cern.ch" port 22

```

**Comment by jhgoh** [comment]
neuron -> GSDC도 timeout됩니다. 
```
ssh ui20.sdfarm.kr -l jhgoh -p 4280
ssh: connect to host ui20.sdfarm.kr port 4280: Connection timed out
```

**Comment by JunwonTomOh** [comment]
**외부에서 neuron으로 scp 접속시 가능한 것으로 확인 됨.**

![image](https://github.com/nurion4hep/KRE-RnD-Transformer4MET/assets/126056589/9f5409b6-43d7-4c54-bd71-c9f8aee5e124)
![image (1)](https://github.com/nurion4hep/KRE-RnD-Transformer4MET/assets/126056589/c6862922-234a-4dac-9455-8245164fb06b)
