### ISSUE TITLE
Find a UFO for dark matter

### ISSUE THREAD

**Issue by slowmoyang** [nurion4hep/KSC-RnD-2024-Transformer4MET#8]
find a UFO for a dark matter

**Comment by jhgoh** [comment]
Link to the FeynRules model database: 
- https://feynrules.irmp.ucl.ac.be/wiki/ModelDatabaseMainPage
- NLO models: https://feynrules.irmp.ucl.ac.be/wiki/NLOModels

**Comment by slowmoyang** [comment]
let's generate simplified spin-0 DM with s-channel
